# Site settings
title: voidm4p's Blog
email: voidm4p@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  👻 void m4p()
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://voidm4p.me' # the base hostname & protocol for your site
github_username: voidm4p

permalink: /:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-algolia
  - jekyll-paginate
  - jekyll-archives
  - jemoji

# Paginate V1
paginate: 256
paginate_path: '/page/:num/'

# Paginate V2
pagination:
  enabled: true
  debug: false
  per_page: 7
  permalink: '/page/:num/'
  sort_reverse: true
  trail:
    before: 2
    after: 2

jekyll-archives:
  enabled:
    - month
    - categories
    - tags
  layouts:
    month: archive-month
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    month: /:year/:month/
    category: /category/:name/
    tag: /tag/:name/

algolia:
  application_id: N8HJNBZA6P
  index_name: jekyll_blog
